services: 
 node_exporter:
    container_name: node_exporter
    image: prom/node-exporter
    command: 
      - '--path.rootfs=/host'
    ports:
      - '9101:9100'
    volumes:
      - '/:/host:ro,rslave'
